apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::203918861424:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-I48wJFgMA8hN
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::203918861424:user/prudvi
      username: prudvi
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-06T09:26:46Z"
  name: aws-auth
  namespace: kube-system
  uid: 6727ce43-6e87-4a95-a32f-b3a17e3299ac
